version: '3.8'
services:
  backend:
    build:
      context: ./backend_diving
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_JWT_SECRET: ${SPRING_DATASOURCE_JWT_SECRET}
    depends_on:
      - bazadanych
    volumes:
      - backend_uploads:/app/upload_directory  # Nazwany wolumen

  bazadanych:
    image: postgres:10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend_diving
      dockerfile: Dockerfile
    ports:
      - "3000:8080"  # Mapujemy port 3000 lokalnie na port 8080 w kontenerze
    environment:
      - PORT=8080

volumes:
  pgdata:
  backend_uploads:  # Nazwany wolumen
